# Generated by Django 4.0.4 on 2022-04-22 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('headline', models.TextField()),
                ('link', models.TextField()),
                ('source', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('date_of_query', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Queries',
            },
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite', models.BooleanField(default=False)),
                ('date_of_fav', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article')),
            ],
            options={
                'verbose_name_plural': 'Saved Articles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('articles', models.ManyToManyField(through='news.Saved', to='news.article')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddField(
            model_name='saved',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.user'),
        ),
        migrations.AddField(
            model_name='article',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.query'),
        ),
    ]
