# Generated by Django 4.0.4 on 2022-04-22 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savedarticles', to='news.article'),
        ),
    ]
